Repository CodeYourFuture/legodi-2.0, pull requests merged in 2018-08, with the labels that each got.

#75 Connect navigator state to redux
  app/App.js
  app/navigation/MainTabNavigator.js
  app/package.json
  app/redux/reducers/nav.js
  app/redux/store/rootReducer.js
  app/redux/store/store.js
  app/yarn.lock
Labels: Review me

#80 fix articles translating issue after used real API
  app/helpers/api.js
Labels: Done, Review me

#81 use weegie game with real API
  app/helpers/api.js
Labels: Done, Review me, question

#90 Add db client for languages
  README.md
  docker-compose.yml
  server/__integration_tests/api/languages.spec.js
  server/__integration_tests/dbClients/languagesDB.spec.js
  server/app.js
  server/dbClients/connection.js
  server/dbClients/languageDB.js
  server/knexfile.js
  server/migrations/20180808152913_articles.js
  server/package-lock.json
  server/package.json
  server/routes/admin/languages/index.js
Labels: Review me

#91 Fix displaying articles at asylum category issues
  app/screens/AddArticle/AddArticle.js
  app/screens/Article/Article.js
  app/screens/Article/ArticleStyle.js
  server/routes/api.js
Labels: Review me

#93 Create users reset API and usersDB tests
  server/__integration_tests/api/users.spec.js
  server/__integration_tests/dbClients/usersDB.spec.js
  server/dbClients/usersDB.js
Labels: Review me

#92 Create users table and its seed data
  server/migrations/20180808152913_articles.js
  server/seeds/languages_categories.js
Labels: Review me

#94 Create usersDB connection functions and users reset API
  server/__integration_tests/api/languages.spec.js
  server/__integration_tests/api/users.spec.js
  server/__integration_tests/dbClients/usersDB.spec.js
  server/app.js
  server/dbClients/usersDB.js
  server/routes/admin/users/index.js
Labels: Review me

#101 Create article API endpoints and articleDB connections
  server/app.js
  server/dbClients/articlesDB.js
  server/routes/api/articles/index.js
  server/seeds/index.js
Labels: Review me

#102 Update seed with old legodie api data
  server/dbClients/categoriesDB.js
  server/migrations/20180808152913_tables.js
  server/package.json
  server/routes/api/categories/index.js
  server/seeds/data/articles.js
  server/seeds/data/categories.js
  server/seeds/data/languages.js
  server/seeds/data/users.js
  server/seeds/data/weegie.js
  server/seeds/index.js
Labels: Review me

#104 create API endpoint to get list of categories filtered by language
  server/dbClients/categoriesDB.js
  server/routes/api/categories/index.js
Labels: Review me

#103 Create endpoint to get list of articles for single category
  server/dbClients/categoriesDB.js
  server/routes/api/categories/index.js
Labels: Review me

#105 add article validation on the client side
  app/screens/AddArticle/AddArticle.js
Labels: Review me

#106 Update app to use new categories endpoint
  app/helpers/api.js
  app/screens/ArticlesListScreen/ArticlesListScreen.js
  app/screens/CategoriesList/CategoriesList.js
  app/screens/SettingsScreen/SettingsScreen.js
  server/dbClients/languageDB.js
  server/dbClients/weegieQuestionDB.js
  server/routes/admin/language/index.js
  server/routes/api/articles/index.js
  server/routes/api/users/index.js
Labels: Review me

#108 Update Weegie seed data and endpoints
  app/helpers/api.js
  app/screens/WeegieGameScreen/WeegieGameScreen.js
  server/migrations/20180808152913_tables.js
  server/routes/api/weegie/index.js
  server/seeds/data/weegie.js
Labels: Review me

#109 use language API at app and update categories and language seed data
  app/helpers/api.js
  app/redux/actions/categoriesActions.js
  app/redux/actions/languagesActions.js
  app/redux/actions/types.js
  app/redux/reducers/languages.js
  app/redux/store/rootReducer.js
  app/screens/CategoriesList/CategoriesList.js
  app/screens/SettingsScreen/SettingsScreen.js
  server/__integration_tests/api/weegie.spec.js
  server/app.js
  server/dbClients/articlesDB.js
  server/dbClients/categoriesDB.js
  server/dbClients/languageDB.js
  server/dbClients/usersDB.js
  server/dbClients/weegieQuestionDB.js
  server/migrations/20180808152913_tables.js
  server/routes/admin/language/index.js
  server/routes/admin/users/index.js
  server/routes/admin/weegie/index.js
  server/routes/api/articles/index.js
  server/routes/api/categories/index.js
  server/routes/api/languages/index.js
  server/routes/api/users/index.js
  server/routes/api/weegie/index.js
  server/seeds/data/articles.js
  server/seeds/data/categories.js
  server/seeds/data/languages.js
  server/seeds/data/users.js
  server/seeds/data/weegie.js
  server/seeds/index.js
Labels: Review me

#112 create Node authentication API
  server/dbClients/usersDB.js
  server/package-lock.json
  server/package.json
  server/routes/api/authentication/config.js
  server/routes/api/authentication/index.js
  server/routes/api/users/index.js
Labels: Review me

#118 Add color constants to all screens
  app/components/CategoriesIcon/CategoriesIcon.js
  app/components/CategoriesIcon/IconStyles.js
  app/constants/Colors.js
  app/navigation/MainTabNavigator.js
  app/navigation/helpers.js
  app/screens/AboutScreen/AboutScreenStyle.js
  app/screens/AddArticle/AddArticle.js
  app/screens/Article/Article.js
  app/screens/Article/ArticleStyle.js
  app/screens/ArticlesListScreen/ArticleListStyles.js
  app/screens/ArticlesListScreen/ArticlesListScreen.js
  app/screens/CategoriesList/CategoryListStyles.js
  app/screens/HomeScreen/HomeScreen.js
  app/screens/HomeScreen/HomeStyles.js
  app/screens/SettingsScreen/SettingStyles.js
  app/screens/WeegieGameScreen/StartWeegieGame.js
  app/screens/WeegieGameScreen/StartWeegieStyle.js
  app/screens/WeegieGameScreen/WeegieGameScreen.js
  app/screens/WeegieGameScreen/WeegieGameStyle.js
  server/__integration_tests/dbClients/usersDB.spec.js
  server/app.js
  server/dbClients/categoriesDB.js
  server/dbClients/usersDB.js
  server/knexfile.js
  server/routes/admin/articles/index.js
  server/routes/admin/categories/index.js
  server/routes/admin/language/index.js
  server/routes/api/authentication/config.js
  server/routes/api/authentication/index.js
  server/routes/api/users/index.js
Labels: Review me
